### ISSUE TITLE
Error message in course 12, 14 and 15

### ISSUE THREAD

**Issue by sultanakaneel** [krcarriere/PSYCH#6]
Hi,

I get the following error

Error in .f(.x[[i]], ...) : object 'CONDITION' not found

**Comment by krcarriere** [comment]
Weird. I don’t get it when I’m editing the course but through Swirl itself i do get it. More quizzical because capitalized coding like CONDITION is not my style which points to it not being a package side issue...

**Comment by rednael17** [comment]
Any solutions? I get a similar error, but only  in course 12. 14 and 15 are fine for me.

Error: Can't rename columns that don't exist.
x The column `CONDITION` doesn't exist.

**Comment by krcarriere** [comment]
A completely revised version of this course will be completed by August 2023.
